name: Compile grpc

on: 
  workflow_dispatch:

jobs:
  Compile_and_release:
    name: Compile and release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile
        run: |
          export INSTALL_DIR=$HOME/.local
          mkdir -p $INSTALL_DIR
          export PATH="$INSTALL_DIR/bin:$PATH"
          sudo apt install -y cmake
          sudo apt install -y build-essential autoconf libtool pkg-config
          cd $HOME
          git clone --recurse-submodules -b v1.61.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc.git
          cd grpc
          mkdir -p cmake/build
          pushd cmake/build
          cmake -DgRPC_INSTALL=ON \
                -DgRPC_BUILD_TESTS=OFF \
                -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
                ../..
          make -j 4
          make install
          popd
          tree $HOME/.local
          
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: $HOME/.local/bin/grpc_cpp_plugin
          tag: grpc
